DROP TABLE IF EXISTS school_classroom;
DROP TABLE IF EXISTS professor_subject;
DROP TABLE IF EXISTS professor;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS school;
DROP TABLE IF EXISTS persons;
DROP TABLE IF EXISTS subjects_classroom;
DROP TABLE IF EXISTS classroom;
DROP TABLE IF EXISTS subjects;
DROP TABLE IF EXISTS address;

