version: '3.8'
services:
  database:
    image: 'postgres:14.2'
    container_name: 'postgres'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=schoolplus
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/extensions/:/docker-entrypoint-initdb.d/
    ports:
      - '5454:5432'
    networks:
      - app
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    links:
      - database
    networks:
      - app
volumes:
  db-data:
    driver: local
networks:
  app:
    driver: bridge