version: '3'
services:
  database:
    image: 'postgres:14'
    container_name: 'postgres'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=schoolplus
    volumes:
      - ./data/db/postgres:/data/db
      - ./db/extensions/:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'
    networks:
      - app
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    links:
      - database
    networks:
      - app
networks:
  app:
    driver: bridge