version: '3.8'
services:
  database:
    image: 'postgres:14.2'
    container_name: 'postgres'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=schoolplus
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/extensions/:/docker-entrypoint-initdb.d/
    ports:
      - '5454:5432'
    networks:
      - app

  backend:
    container_name: backend
    image: cosmtrek/air
    working_dir: /app
    depends_on:
      - database
    links:
      - database
    volumes:
      - ./:/app
    networks:
      - app
    environment:
      - DB_URI="postgres://root:secret@localhost:5454/schoolplus?sslmode=disable"
      - PORT=8080

  proxy:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./config/nginx:/etc/nginx
    networks:
      - app

volumes:
  db-data:
    driver: local

networks:
  app:
    driver: bridge