version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'mongodb'
    environment:
      - MONGO_INITDB_DATABASE=schoolplus
    volumes:
      - ./data/db/mongo:/data/db
    ports:
      - '27017-27019:27017-27019'
    networks:
      - base
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - base
networks:
  base:
    driver: bridge