version: '3'

env:
  PORT: 8080

tasks:
  run:
    desc: run project
    cmds:
      - docker-compose up -d
  local:
    desc: run database
    cmds:
      - docker-compose up -d database

  build-and-run:
    desc: build and run the project
    cmds:
      - docker-compose up --build -d
  db:
    desc: run db on docker
    cmds:
      - docker-compose up -d --build database

  clear:
    desc: clear docker containers
    cmds:
      - docker-compose down
      - echo "Done! 👋🏼"

  setup:
    desc: setup environment to first run
    cmds:
      - task: db
      - task: migrate-up
      - task: run

  migrate-up:
    desc: run migrations on database
    cmds:
      - migrate -database ${DB_URI} -path db/migrations -verbose up
  migrate-down:
    desc: remove migrations on database
    cmds:
      - migrate -database ${DB_URI} -path db/migrations -verbose down

  create-table:
    desc: create a new table to be available on migration-up
    cmds:
      - migrate create -ext sql -dir db/migrations -seq {{.CLI_ARGS}}
  force:
    desc: reset migrations state to version specified
    cmds:
      - migrate -database ${DB_URI} -path db/migrations force {{.CLI_ARGS}}