version: '3'

env:
  PORT: 8080
  #DB_URI: postgres://jlsfrbek:41YTk-sbD-OIQyz7Odh9E7BIksrvHhu0@babar.db.elephantsql.com:5432/jlsfrbek
  DB_URI: postgres://root:secret@localhost:5454/schoolplus?sslmode=disable

tasks:
  run:
    desc: run project locally and db on docker
    cmds:
      - task: db
      - go run cmd/http/main.go

  db:
    desc: run db on docker
    cmds:
      - docker-compose up -d --build database

  clear:
    desc: clear docker containers
    cmds:
      - docker-compose down
      - echo "Done! 👋🏼"

  setup:
    desc: setup environment to first run
    cmds:
      - task: db
      - task: migrate-up
      - task: run

  migrate-up:
    desc: run migrations on database
    cmds:
      - migrate -database ${DB_URI} -path db/migrations up
  migrate-down:
    desc: remove migrations on database
    cmds:
      - migrate -database ${DB_URI} -path db/migrations down

  create-table:
    desc: create a new table to be available on migration-up
    cmds:
      - migrate create -ext sql -dir db/migrations -seq {{.CLI_ARGS}}
  force:
    desc: reset migrations state to version specified
    cmds:
      - migrate -database ${DB_URI} -path db/migrations force {{.CLI_ARGS}}